// This file is generated by Slice Machine. Update with care!

import Aanbod from './Aanbod';
import AfbeeldingTekst from './AfbeeldingTekst';
import Inspiratie from './Inspiratie';
import Kolommen from './Kolommen';
import Quote from './Quote';
import Tekst from './Tekst';
import TekstDubbeleAfbeelding from './TekstDubbeleAfbeelding';

export {
	Aanbod,
	AfbeeldingTekst,
	Inspiratie,
	Kolommen,
	Quote,
	Tekst,
	TekstDubbeleAfbeelding,
};

export const components = {
	aanbod: Aanbod,
	afbeelding_tekst: AfbeeldingTekst,
	inspiratie: Inspiratie,
	kolommen: Kolommen,
	quote: Quote,
	tekst: Tekst,
	tekst_dubbele_afbeelding: TekstDubbeleAfbeelding,
};
